variable "dockerapp_vpc" {}
variable "my_ip" {}
variable "docker_container_port" {}
variable "env_prefix" {}
variable "image_name" {}
variable "public_key_location" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "avail_zone" {}
